---
version: "3.8"
services:
  hello_world:
      image: hello-world
  duckdns:
      image: ghcr.io/linuxserver/duckdns:version-369fbd5c
      container_name: duckdns
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Amsterdam
        - SUBDOMAINS=kna-historie
        - TOKEN=11afd534-1ff8-4779-989d-1bf4f25561f3
        - LOG_FILE=false #optional
  mariadb:
    image: mariadb:10.11.6
    container_name: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - TZ=Europe/Amsterdam
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - PUID=1000
      - PGID=1000

volumes:
  resources:
    driver: local
    driver_opts:
      type: none
      device: ${DIR_RESOURCES}
      o: "bind,rw"
  db:
    driver: local
    driver_opts:
      type: none
      device: ${DIR_MARIADB}
      o: "bind,rw"
